services:
  api-gateway:
    build: ./api-gateway
    environment:
      SERVICE_NAME: api-gateway
      CATALOG_URL: http://catalog-service:8080
      SEARCH_URL: http://search-service:8080
      ORDER_URL: http://order-service:8080
      INVENTORY_URL: http://inventory-service:8080
    ports:
      - "8080:8080"
    depends_on:
      - catalog-service
      - search-service
      - order-service
      - inventory-service

  catalog-service:
    build: ./catalog-service
    environment:
      SERVICE_NAME: catalog-service

  inventory-service:
    build: ./inventory-service
    environment:
      SERVICE_NAME: inventory-service

  order-service:
    build: ./order-service
    environment:
      SERVICE_NAME: order-service
      CATALOG_URL: http://catalog-service:8080
      INVENTORY_URL: http://inventory-service:8080
    depends_on:
      - catalog-service
      - inventory-service

  search-service:
    build: ./search-service
    environment:
      SERVICE_NAME: search-service
      CATALOG_URL: http://catalog-service:8080
    depends_on:
      - catalog-service
