apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shopflow

commonLabels:
  app.kubernetes.io/part-of: shopflow
  shopflow.io/domain: risk

resources:
  - configmap.yaml
  - fraud-service-deployment.yaml
  - review-service-deployment.yaml
